# https://travis-ci.org/tgbugs/pyontutils
sudo: false
language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
branches:
  only:
    - dev
    - master
  git:
    depth: 3

python:
  - 3.6

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - mkdir build
  - pushd build
  - wget https://raw.githubusercontent.com/tgbugs/pyontutils/master/scigraph/nifstd_curie_map.yaml
  - wget https://raw.githubusercontent.com/tgbugs/pyontutils/master/scigraph/graphload.yaml.template
  - popd

install:
  - pip install pipenv
  - pipenv install --system --skip-lock pyontutils

script:
  #- pipenv run ipython -c "__import__('pyontutils.config').config.bootstrap_config()"
  - pipenv run ontload graph NIF-Ontology NIF -z build -l "${TRAVIS_BUILD_DIR}/../" -O SciGraph -B master -b ${TRAVIS_BRANCH} -t "${TRAVIS_BUILD_DIR}/build/graphload.yaml.template" -u "${TRAVIS_BUILD_DIR}/build/nifstd_curie_map.yaml" 

after_success:
  - echo "scp the artifacts somewhere"
